# Default Configuration for WirelessPenTestLib

# General Settings
general:
  interface: "wlan0mon"
  log_level: "INFO"
  report_directory: "reports"

# Scanner Settings
scanners:
  encryption_scanner:
    scan_duration: 15
  auth_bypass_scanner:
    scan_duration: 10
  dos_scanner:
    scan_duration: 10

# Exploit Settings
exploits:
  session_hijacking:
    max_packets: 100
  credential_extraction:
    capture_duration: 20
  payload_delivery:
    payload_types: ["reverse_shell", "malicious_script"]
    default_duration: 10

# UI Settings
ui:
  theme: "default"
